### PR TITLE
Update night.toml

### PR DESCRIPTION
**Pull request by Stekovaya**
I forgot add `unzip` to `packages`, sorry

### CODE REVIEW

**Comment by DynamicSquid** [comment]
oh

**Comment by DynamicSquid** [comment]
wait so do I have to make a new pull request?

**Comment by Stekovaya** [comment]
no

**Comment by DynamicSquid** [comment]
I just have to edit it?

**Comment by Stekovaya** [comment]
merge only, but wait i found code miss

**Comment by DynamicSquid** [comment]
can I merge now?

**Comment by Stekovaya** [comment]
ok merge please

**Comment by Stekovaya** [comment]
waittt test failed by permission

**Comment by Stekovaya** [comment]
i make new pull request sorry

**Pull request merged**
