### PR TITLE
Update night.toml

### PR DESCRIPTION
**Pull request by Stekovaya**

### CODE REVIEW

**Comment by DynamicSquid** [comment]
cool! so I just merge this with master, then open a pull request in the orignial polygott repo?

**Comment by Stekovaya** [comment]
yes :)

**Comment by DynamicSquid** [comment]
okay, but what do I do next? codemonkey says that's only the backend, what about the front end?

**Comment by Stekovaya** [comment]
idk, polygott is for docker...

**Comment by DynamicSquid** [comment]
oh, okay, so once I do this, the language will be on repl.it servers, but you can't chose it like an actual language?

**Comment by Stekovaya** [comment]
***probably*** yes.

**Comment by DynamicSquid** [comment]
oh it's fine, I'm not good at any of this stuff lol. I'll send in the pr

**Pull request merged**
